### ISSUE TITLE
SecureLocalStorage.java not found using ionic package build android command

### ISSUE THREAD

**Issue by PhilHuot** [dickverweij/nl-afas-cordova-plugin-secureLocalStorage#1]
Hi,

I'm having trouble using the `ionic package build android` command with your plugin. It seems like ionic is searching for the SecureLocalStorage.java file in SecureLocalStorage/ but it is actually in secureLocalStorage/ (see the typo).

I tried to uninstall and re-install the plugin, I tried to install it with Cordova or Ionic but the result is the same.

Any help would be appreciated. Thanks in advance.

Here is the error:

`Installing "nl-afas-cordova-plugin-securelocalstorage" for android
Dependent plugin "es6-promise-plugin" already installed on android.
Failed to install 'nl-afas-cordova-plugin-securelocalstorage':CordovaError: Uh oh!
"/home/package/workspace/apps-95ca3183-8/cordova/plugins/nl-afas-cordova-plugin-securelocalstorage/src/android/nl/afas/cordova/plugin/SecureLocalStorage/SecureLocalStorage.java" not found!
    at copyFile (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/lib/pluginHandlers.js:182:36)
    at copyNewFile (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/lib/pluginHandlers.js:214:5)
    at handlers.source-file.install (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/lib/pluginHandlers.js:34:13)
    at Object.ActionStack.process (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Api.addPlugin (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/Api.js:205:20)
    at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:605:6)
    at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:403:28
    at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
Error: Uh oh!
"/home/package/workspace/apps-95ca3183-8/cordova/plugins/nl-afas-cordova-plugin-securelocalstorage/src/android/nl/afas/cordova/plugin/SecureLocalStorage/SecureLocalStorage.java" not found!`

**Comment by dickverweij** [comment]
On what system you are developing?

Van: PhilHuot [mailto:notifications@github.com]
Verzonden: woensdag 4 mei 2016 16:07
Aan: dickverweij/nl-afas-cordova-plugin-securelocalstorage nl-afas-cordova-plugin-securelocalstorage@noreply.github.com
Onderwerp: [dickverweij/nl-afas-cordova-plugin-securelocalstorage] SecureLocalStorage.java not found using ionic package build android command (#1)

Hi,

I'm having trouble using the ionic package build android command with your plugin. It seems like ionic is searching for the SecureLocalStorage.java file in SecureLocalStorage/ but it is actually in secureLocalStorage/ (see the typo).

I tried to uninstall and re-install the plugin, I tried to install it with Cordova or Ionic but the result is the same.

Any help would be appreciated. Thanks in advance.

Here is the error:

Installing "nl-afas-cordova-plugin-securelocalstorage" for android
Dependent plugin "es6-promise-plugin" already installed on android.
Failed to install 'nl-afas-cordova-plugin-securelocalstorage':CordovaError: Uh oh!
"/home/package/workspace/apps-95ca3183-8/cordova/plugins/nl-afas-cordova-plugin-securelocalstorage/src/android/nl/afas/cordova/plugin/SecureLocalStorage/SecureLocalStorage.java" not found!
at copyFile (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/lib/pluginHandlers.js:182:36)
at copyNewFile (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/lib/pluginHandlers.js:214:5)
at handlers.source-file.install (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/lib/pluginHandlers.js:34:13)
at Object.ActionStack.process (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
at Api.addPlugin (/home/package/workspace/apps-95ca3183-8/cordova/platforms/android/cordova/Api.js:205:20)
at handleInstall (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:605:6)
at /usr/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:403:28
at _fulfilled (/usr/lib/node_modules/cordova/node_modules/q/q.js:787:54)
at self.promiseDispatch.done (/usr/lib/node_modules/cordova/node_modules/q/q.js:816:30)
at Promise.promise.promiseDispatch (/usr/lib/node_modules/cordova/node_modules/q/q.js:749:13)
Error: Uh oh!
"/home/package/workspace/apps-95ca3183-8/cordova/plugins/nl-afas-cordova-plugin-securelocalstorage/src/android/nl/afas/cordova/plugin/SecureLocalStorage/SecureLocalStorage.java" not found!

**Comment by PhilHuot** [comment]
On Mac

**Comment by dickverweij** [comment]
Could you try version 0.1.9? I;ve corrected the dir name for case sensitive os-es

Van: PhilHuot [mailto:notifications@github.com]
Verzonden: woensdag 4 mei 2016 16:26
Aan: dickverweij/nl-afas-cordova-plugin-securelocalstorage nl-afas-cordova-plugin-securelocalstorage@noreply.github.com
CC: Dick Verweij D.Verweij@afas.nl; Comment comment@noreply.github.com
Onderwerp: Re: [dickverweij/nl-afas-cordova-plugin-securelocalstorage] SecureLocalStorage.java not found using ionic package build android command (#1)

On Mac

**Comment by PhilHuot** [comment]
It's working like a charm now, version 0.1.9 fixed the problem. Thank you very much!
